name: jacked
description: "A free workout tracking app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  # update also in CI
  flutter: ">=3.38.4 <4.0.0"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.4.0

flutter:
  uses-material-design: true

  # Enables generation of localized strings from arb files
  generate: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans/static/OpenSans-Regular.ttf
        - asset: assets/OpenSans/static/OpenSans-Italic.ttf
          style: italic
        - asset: assets/OpenSans/static/OpenSans-Bold.ttf
          weight: 700
